In [40]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\user\eda\penguins(c)\venv\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\user\eda\penguins(c)\venv\lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in c:\users\user\eda\penguins(c)\venv\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\user\eda\penguins(c)\venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\user\eda\penguins(c)\venv\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [45]:
df=pd.read_csv('penguins.csv')

In [46]:
df

,id,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...,...
339,339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [47]:
df.isnull().sum()

id                    0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [48]:
df.drop(['id','year'],axis=1,inplace=True)

In [49]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female
...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female

In [50]:
df.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [51]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female
...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female

In [52]:
df['bill_length_mm'].median()

np.float64(44.45)

In [53]:
df['bill_length_mm'].unique()

array([39.1, 39.5, 40.3,  nan, 36.7, 39.3, 38.9, 39.2, 34.1, 42. , 37.8,
       41.1, 38.6, 34.6, 36.6, 38.7, 42.5, 34.4, 46. , 37.7, 35.9, 38.2,
       38.8, 35.3, 40.6, 40.5, 37.9, 37.2, 40.9, 36.4, 42.2, 37.6, 39.8,
       36.5, 40.8, 36. , 44.1, 37. , 39.6, 37.5, 42.3, 40.1, 35. , 34.5,
       41.4, 39. , 35.7, 41.3, 41.6, 35.5, 41.8, 33.5, 39.7, 45.8, 42.8,
       36.2, 42.1, 42.9, 35.1, 37.3, 36.3, 36.9, 38.3, 34. , 38.1, 33.1,
       43.2, 41. , 45.6, 42.7, 40.2, 35.2, 41.5, 38.5, 43.1, 36.8, 35.6,
       32.1, 40.7, 46.1, 50. , 48.7, 47.6, 46.5, 45.4, 46.7, 43.3, 46.8,
       49. , 45.5, 48.4, 49.3, 49.2, 46.2, 50.2, 45.1, 46.3, 44.5, 47.8,
       48.2, 47.3, 59.6, 49.1, 42.6, 44.4, 44. , 49.6, 45.3, 50.5, 43.6,
       44.9, 45.2, 46.6, 48.5, 50.1, 45. , 43.8, 50.4, 45.7, 54.3, 49.8,
       49.5, 43.5, 50.7, 47.7, 46.4, 48.6, 47.5, 51.1, 52.5, 47.4, 50.8,
       43.4, 51.3, 52.1, 52.2, 49.4, 46.9, 55.9, 47.2, 41.7, 53.4, 48.1,
       51.5, 55.1, 48.8, 49.9, 52.7, 51.7, 47. , 52. , 45.9, 50.3, 58. ,
       42.4, 50.6, 52.8, 54.2, 51. , 49.7, 53.5, 50.9, 51.4, 51.9, 55.8])

In [54]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female

In [55]:
cols=['bill_length_mm','bill_depth_mm','flipper_length_mm','body_mass_g']
df[cols]=df[cols].fillna(df[cols].median())

In [56]:
df.isna().sum()

species               0
island                0
bill_length_mm        0
bill_depth_mm         0
flipper_length_mm     0
body_mass_g           0
sex                  11
dtype: int64

In [57]:
df['sex'] = (df['sex'] == 'female').astype(int)

In [58]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10,18.7,181.0,3750.0,0
1,Adelie,Torgersen,39.50,17.4,186.0,3800.0,1
2,Adelie,Torgersen,40.30,18.0,195.0,3250.0,1
3,Adelie,Torgersen,44.45,17.3,197.0,4050.0,0
4,Adelie,Torgersen,36.70,19.3,193.0,3450.0,1
...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.80,19.8,207.0,4000.0,0
340,Chinstrap,Dream,43.50,18.1,202.0,3400.0,1
341,Chinstrap,Dream,49.60,18.2,193.0,3775.0,0
342,Chinstrap,Dream,50.80,19.0,210.0,4100.0,0
343,Chinstrap,Dream,50.20,18.7,198.0,3775.0,1

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    int64
dtypes: float64(4), int64(1), str(2)
memory usage: 18.9 KB

In [60]:
df['sex'] = df['sex'].replace(['female','male'],[1,0])

In [61]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10,18.7,181.0,3750.0,0
1,Adelie,Torgersen,39.50,17.4,186.0,3800.0,1
2,Adelie,Torgersen,40.30,18.0,195.0,3250.0,1
3,Adelie,Torgersen,44.45,17.3,197.0,4050.0,0
4,Adelie,Torgersen,36.70,19.3,193.0,3450.0,1
...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.80,19.8,207.0,4000.0,0
340,Chinstrap,Dream,43.50,18.1,202.0,3400.0,1
341,Chinstrap,Dream,49.60,18.2,193.0,3775.0,0
342,Chinstrap,Dream,50.80,19.0,210.0,4100.0,0
343,Chinstrap,Dream,50.20,18.7,198.0,3775.0,1

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    int64
dtypes: float64(4), int64(1), str(2)
memory usage: 18.9 KB

In [63]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10,18.7,181.0,3750.0,0
1,Adelie,Torgersen,39.50,17.4,186.0,3800.0,1
2,Adelie,Torgersen,40.30,18.0,195.0,3250.0,1
3,Adelie,Torgersen,44.45,17.3,197.0,4050.0,0
4,Adelie,Torgersen,36.70,19.3,193.0,3450.0,1
...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.80,19.8,207.0,4000.0,0
340,Chinstrap,Dream,43.50,18.1,202.0,3400.0,1
341,Chinstrap,Dream,49.60,18.2,193.0,3775.0,0
342,Chinstrap,Dream,50.80,19.0,210.0,4100.0,0
343,Chinstrap,Dream,50.20,18.7,198.0,3775.0,1

In [64]:
from sklearn.preprocessing import OneHotEncoder
encoder= OneHotEncoder(sparse_output=False)
encoded= encoder.fit_transform(df[['species','island']])
edf=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
df=df.drop(['species','island'],axis=1)
df = pd.concat([df,edf], axis=1)

In [65]:
print(df.columns)

Index(['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g',
       'sex', 'species_Adelie', 'species_Chinstrap', 'species_Gentoo',
       'island_Biscoe', 'island_Dream', 'island_Torgersen'],
      dtype='str')

In [66]:
df

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_Adelie,species_Chinstrap,species_Gentoo,island_Biscoe,island_Dream,island_Torgersen
0,39.10,18.7,181.0,3750.0,0,1.0,0.0,0.0,0.0,0.0,1.0
1,39.50,17.4,186.0,3800.0,1,1.0,0.0,0.0,0.0,0.0,1.0
2,40.30,18.0,195.0,3250.0,1,1.0,0.0,0.0,0.0,0.0,1.0
3,44.45,17.3,197.0,4050.0,0,1.0,0.0,0.0,0.0,0.0,1.0
4,36.70,19.3,193.0,3450.0,1,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
339,55.80,19.8,207.0,4000.0,0,0.0,1.0,0.0,0.0,1.0,0.0
340,43.50,18.1,202.0,3400.0,1,0.0,1.0,0.0,0.0,1.0,0.0
341,49.60,18.2,193.0,3775.0,0,0.0,1.0,0.0,0.0,1.0,0.0
342,50.80,19.0,210.0,4100.0,0,0.0,1.0,0.0,0.0,1.0,0.0
343,50.20,18.7,198.0,3775.0,1,0.0,1.0,0.0,0.0,1.0,0.0

In [67]:
df

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_Adelie,species_Chinstrap,species_Gentoo,island_Biscoe,island_Dream,island_Torgersen
0,39.10,18.7,181.0,3750.0,0,1.0,0.0,0.0,0.0,0.0,1.0
1,39.50,17.4,186.0,3800.0,1,1.0,0.0,0.0,0.0,0.0,1.0
2,40.30,18.0,195.0,3250.0,1,1.0,0.0,0.0,0.0,0.0,1.0
3,44.45,17.3,197.0,4050.0,0,1.0,0.0,0.0,0.0,0.0,1.0
4,36.70,19.3,193.0,3450.0,1,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
339,55.80,19.8,207.0,4000.0,0,0.0,1.0,0.0,0.0,1.0,0.0
340,43.50,18.1,202.0,3400.0,1,0.0,1.0,0.0,0.0,1.0,0.0
341,49.60,18.2,193.0,3775.0,0,0.0,1.0,0.0,0.0,1.0,0.0
342,50.80,19.0,210.0,4100.0,0,0.0,1.0,0.0,0.0,1.0,0.0
343,50.20,18.7,198.0,3775.0,1,0.0,1.0,0.0,0.0,1.0,0.0

In [68]:
df.to_csv('processed_data.csv',index=False)

In [69]:
ndf=pd.read_csv('processed_data.csv')

In [72]:
def check_data(ndf):
    for col in ndf.columns:
        print(f'\nColumns:{col}')

        if ndf[col].nunique() < 10:
            print('\nCategorical distribution(%): ')
            print(df[col].value_counts(normalize=True)*100)
        else:
            print('continous summary: ')
            print(ndf[col].describe())
check_data(ndf)

Columns:bill_length_mm
continous summary:
count    344.000000
mean      43.925000
std        5.443792
min       32.100000
25%       39.275000
50%       44.450000
75%       48.500000
max       59.600000
Name: bill_length_mm, dtype: float64

Columns:bill_depth_mm
continous summary:
count    344.000000
mean      17.152035
std        1.969060
min       13.100000
25%       15.600000
50%       17.300000
75%       18.700000
max       21.500000
Name: bill_depth_mm, dtype: float64

Columns:flipper_length_mm
continous summary:
count    344.000000
mean     200.892442
std       14.023826
min      172.000000
25%      190.000000
50%      197.000000
75%      213.000000
max      231.000000
Name: flipper_length_mm, dtype: float64

Columns:body_mass_g
continous summary:
count     344.000000
mean     4200.872093
std       799.696532
min      2700.000000
25%      3550.000000
50%      4050.000000
75%      4750.000000
max      6300.000000
Name: body_mass_g, dtype: float64

Columns:sex

Categorical distribution(%):
sex
0    52.034884
1    47.965116
Name: proportion, dtype: float64

Columns:species_Adelie

Categorical distribution(%):
species_Adelie
0.0    55.813953
1.0    44.186047
Name: proportion, dtype: float64

Columns:species_Chinstrap

Categorical distribution(%):
species_Chinstrap
0.0    80.232558
1.0    19.767442
Name: proportion, dtype: float64

Columns:species_Gentoo

Categorical distribution(%):
species_Gentoo
0.0    63.953488
1.0    36.046512
Name: proportion, dtype: float64

Columns:island_Biscoe

Categorical distribution(%):
island_Biscoe
0.0    51.162791
1.0    48.837209
Name: proportion, dtype: float64

Columns:island_Dream

Categorical distribution(%):
island_Dream
0.0    63.953488
1.0    36.046512
Name: proportion, dtype: float64

Columns:island_Torgersen

Categorical distribution(%):
island_Torgersen
0.0    84.883721
1.0    15.116279
Name: proportion, dtype: float64

In [75]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.ensemble import RandomForestRegressor , GradientBoostingRegressor
from sklearn.linear_model import LinearRegression , Lasso , Ridge
from sklearn.neighbors import KNeighborsRegressor

In [76]:
X=ndf.drop(['body_mass_g'],axis=1)
y=ndf['body_mass_g']

In [77]:
models ={
    'Linear Regression':LinearRegression(),
    'Lasso' :Lasso(random_state=42),
    'Ridge':Ridge(random_state=42),

    'Random Forest Regressor':RandomForestRegressor(random_state=42),
    'Gradient Boost Regressor':GradientBoostingRegressor(random_state=42),

    'KNN':KNeighborsRegressor()
}

In [78]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df[['bill_length_mm','bill_depth_mm','flipper_length_mm']]=scaler.fit_transform(df[['bill_length_mm','bill_depth_mm','flipper_length_mm']])

In [79]:
for name, model in models.items():
    try:
        model.fit(X_train,y_train)
        y_pred=model.predict(X_test)

        print(f'\nModel Name: {name}')
        print(f'\nR2 Score: {r2_score(y_test,y_pred):.3f}')
        print(f'\nMean Absolute Error: {mean_absolute_error(y_test,y_pred):.3f}')
        print(f'\nMean Squared Error: {mean_squared_error(y_test,y_pred):.3f}')

    except Exception as e:
        print(f'Model Name: {name} FAILED')
        print(f'ERROR: {e}')

Model Name: Linear Regression

R2 Score: 0.834

Mean Absolute Error: 246.437

Mean Squared Error: 94935.656

Model Name: Lasso

R2 Score: 0.834

Mean Absolute Error: 246.190

Mean Squared Error: 95068.287

Model Name: Ridge

R2 Score: 0.835

Mean Absolute Error: 244.801

Mean Squared Error: 94552.995

Model Name: Random Forest Regressor

R2 Score: 0.789

Mean Absolute Error: 268.518

Mean Squared Error: 120641.910

Model Name: Gradient Boost Regressor

R2 Score: 0.820

Mean Absolute Error: 250.585

Mean Squared Error: 102899.849

Model Name: KNN

R2 Score: 0.773

Mean Absolute Error: 283.116

Mean Squared Error: 129803.261